@startuml
title Usecase for Information system
left to right direction
skinparam packageStyle rect

actor Consumer

rectangle {
  Consumer --> (Share Location)
  (Send Message) ..> (Share Location) : <<include>>
  (Get info about environment) ..> (Share Location) : <<include>>
  (Get info about nearest galleries) ..> (Share Location) : <<include>>
}
@enduml
